[package]
name = "bench"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
anchor-debug = []
custom-heap = []
custom-panic = []
no-log-ix-name = []

[dependencies]
# Written by the benchmark entrypoint in its disposable work directory.
anchor-lang = "=0.0.0"
anchor-spl = "=0.0.0"
